config/routes.rb
Rails.application.routes.draw do
  root :to=> "cats#index"
  resources :cats
  devise_for :users

  devise_scope :user do
    get "/" => "devise/registrations#cancel"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ActiveRecord::Base

  has_many :comments
  validates :name, :about, :traits, :price, presence: true

  # scope :recent, -> { order(created_at: :desc) }
  # scope :today_total, -> { where("created_at >=?", Time.now.beginning_of_day).length }

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :cat
  validates :user_id, :cat_id, :content, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :comments

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
  end

  def show
    @cat = Cat.find(params[:id])
    @comment = @cat.comments.new
  end

  def new
    @cat = Cat.new
  end

  def create
    @cat = Cat.new(cat_params)

    if @cat.save
      flash[:notice] = "Cat posted successfully!"
      redirect_to cats_path
    else
      flash[:alert] = "Something went wrong!"
      render :new
    end
  end

  def edit
    @cat = Cat.find(params[:id])

  end

  def update
    @cat = Cat.find(params[:id])

      if @cat.update(cat_params)
        flash[:notice] = "Cat updated successfully!"
        redirect_to cat_path(@cat)
      else
        flash[:alert] = "Something went wrong!"
        render :edit
      end
  end

  def destroy
    @cat = Cat.find(params[:id])
    if user.admin?
      @cat.comments.each do |comment|
        comment.destroy
      end
      @cat.destroy
      flash[:notice] = "Cat deleted successfully!"
      redirect_to cats_path
    else
      flash[:alert] = "You aren't authorized to do that."
      redirect_to cat_path(@cat)
    end
  end

private
  def cat_params
    params.require(:cat).permit(:name, :about, :traits, :price)
  end
end

app/controllers/comments_controller.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :cat

  validates :user, :cat_id, :content, presence: true

  # scope :recent, -> { order(created_at: :desc) }
  # scope :today_total, -> { where("created_at >=?", Time.now.beginning_of_day).length }

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cats/edit.html.erb
<p>hdhdhd</p>

app/views/cats/index.html.erb
<% if current_user %>
  <%= current_user.user_name %>
  <h5><%= link_to "Sign out", 'users/sign_out', method: :delete %></h5>
<% else %>
  <h5><%= link_to "Sign in", 'users/sign_in' %> </h5>
<% end %>

<h1>Cat List</h1>
<% if @cats.any? %>
  <% @cats.each do |cat| %>
    <div class="cat-name">
      <h3><%= link_to cat.name, cat_path(cat) %></h3>
    </div>
  <% end %>
<% else %>
  <p>sorry, there are no cats yet</p>
<% end %>
<% if current_user.try(:admin?) %>
|  <%= link_to "Add an cat", new_cat_path %>
<% end %>

app/views/cats/new.html.erb
<h5><%= link_to "Back to Cats", cats_path %></h5>


<h1>Add a Cat</h1>
<%= form_for @cat do |f| %>
  <div class="form_group">
    <%= f.label "name", class: "control-label"  %>
    <%= f.text_field :name, class: "form-control"%>
    <br>
    <%= f.label :about, class: "control-label" %>
    <%= f.text_area :about, class: "form-control" %>
    <br>
    <%= f.label :traits, class: "control-label" %>
    <%= f.text_area :traits, class: "form-control" %>
    <br>
    <%= f.label :price, class: "control-label" %>
    <%= number_field(:cat, :price, in: 1.0..200.0, step: 0.5) %>
    <%= f.submit "Add" %>
  </div>
<% end %>

app/views/cats/show.html.erb
<h5><%= link_to "Back to Cats", cats_path %></h5>

<h2><%= @cat.name %></h2>
<br>
<h3>About<%= @cat.name %></h3>
<p><%= @cat.about %></p>
<br>
<h3><%= @cat.name %>'s Traits</h3>
<p><%= @cat.traits %></p>
<br>
<h3><%= @cat.name %>'s Price per weekend:</h3>
<p>$<%= @cat.price %></p>

<% if current_user && current_user.admin %>
  <%= link_to "Edit", '/cats/:id/edit' %> |
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentACat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>